services:
  poneyhot-http-server:
    build:
      context: .
      dockerfile: backend/httpServer/Dockerfile
    volumes:
      - ./dumps:/app/http/dumps
      - ./db:/app/http/db
      - ./.env:/app/.env
      - ./backend/httpServer/nginx.conf:/etc/nginx/nginx.conf
    env_file:
      - .env
    container_name: poneyhot-httpServer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - poneyhot-network

  poneyhot-telegram-bot:
    build:
      context: .
      dockerfile: backend/telegramBot/Dockerfile
    volumes:
      - ./.env:/app/.env
    env_file:
      - .env
    container_name: poneyhot-telegramBot
    restart: unless-stopped
    depends_on:
      - poneyhot-http-server
    networks:
      - poneyhot-network

networks:
  poneyhot-network:
    driver: bridge